apiVersion: v1
kind: Service
metadata:
  name: em-bs
spec:
  selector:
    app: em-bs
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
  type: NodePort
---
apiVersion: apps/v1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: em-bs
  labels:
    app: em-bs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: em-bs
  template:
    metadata:
      labels:
        app: em-bs
    spec:
      containers:
      - name: backend
        image: sureshskit/em-backend
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: registrypullsecret   
---

      